# CMake generated Testfile for 
# Source directory: /home/nathaly/Downloads/gmsh-4.4.1-source
# Build directory: /home/nathaly/Downloads/gmsh-4.4.1-source/build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(../demos/boolean/baffles.geo "./gmsh" "../demos/boolean/baffles.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/boolean.geo "./gmsh" "../demos/boolean/boolean.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/chamfer.geo "./gmsh" "../demos/boolean/chamfer.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/coherence.geo "./gmsh" "../demos/boolean/coherence.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/compsolid.geo "./gmsh" "../demos/boolean/compsolid.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/compsolid2.geo "./gmsh" "../demos/boolean/compsolid2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/extrude.geo "./gmsh" "../demos/boolean/extrude.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/extrude2.geo "./gmsh" "../demos/boolean/extrude2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/fillet.geo "./gmsh" "../demos/boolean/fillet.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/fillet2.geo "./gmsh" "../demos/boolean/fillet2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/fillet3.geo "./gmsh" "../demos/boolean/fillet3.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/fillet4.geo "./gmsh" "../demos/boolean/fillet4.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/fillet_chamfer.geo "./gmsh" "../demos/boolean/fillet_chamfer.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/fragment_numbering.geo "./gmsh" "../demos/boolean/fragment_numbering.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/hybrid_occ_builtin.geo "./gmsh" "../demos/boolean/hybrid_occ_builtin.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/import.geo "./gmsh" "../demos/boolean/import.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/import2.geo "./gmsh" "../demos/boolean/import2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/intersect_line_volume.geo "./gmsh" "../demos/boolean/intersect_line_volume.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/neuron.geo "./gmsh" "../demos/boolean/neuron.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/periodic.geo "./gmsh" "../demos/boolean/periodic.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/periodic_embedded.geo "./gmsh" "../demos/boolean/periodic_embedded.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/pipe.geo "./gmsh" "../demos/boolean/pipe.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/primitives.geo "./gmsh" "../demos/boolean/primitives.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/revolve.geo "./gmsh" "../demos/boolean/revolve.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/revolve2.geo "./gmsh" "../demos/boolean/revolve2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/shell_sewing.geo "./gmsh" "../demos/boolean/shell_sewing.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/simple.geo "./gmsh" "../demos/boolean/simple.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/simple2.geo "./gmsh" "../demos/boolean/simple2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/simple3.geo "./gmsh" "../demos/boolean/simple3.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/simple4.geo "./gmsh" "../demos/boolean/simple4.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/simple5.geo "./gmsh" "../demos/boolean/simple5.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/simple6.geo "./gmsh" "../demos/boolean/simple6.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/simple7.geo "./gmsh" "../demos/boolean/simple7.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/slicer.geo "./gmsh" "../demos/boolean/slicer.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/spherical_surf.geo "./gmsh" "../demos/boolean/spherical_surf.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/spline.geo "./gmsh" "../demos/boolean/spline.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/step_assembly.geo "./gmsh" "../demos/boolean/step_assembly.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/surface_filling.geo "./gmsh" "../demos/boolean/surface_filling.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/thicksolid.geo "./gmsh" "../demos/boolean/thicksolid.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/thrusections.geo "./gmsh" "../demos/boolean/thrusections.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/transfinite.geo "./gmsh" "../demos/boolean/transfinite.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/transform.geo "./gmsh" "../demos/boolean/transform.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/boolean/twist.geo "./gmsh" "../demos/boolean/twist.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/post_processing/compute_area_volume.geo "./gmsh" "../demos/post_processing/compute_area_volume.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/post_processing/lowmem-anim.geo "./gmsh" "../demos/post_processing/lowmem-anim.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/post_processing/plot2d.geo "./gmsh" "../demos/post_processing/plot2d.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/post_processing/view_groups.geo "./gmsh" "../demos/post_processing/view_groups.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/antenna.geo "./gmsh" "../demos/simple_geo/antenna.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/cone.geo "./gmsh" "../demos/simple_geo/cone.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/cube.geo "./gmsh" "../demos/simple_geo/cube.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/filter.geo "./gmsh" "../demos/simple_geo/filter.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/hex.geo "./gmsh" "../demos/simple_geo/hex.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/homology.geo "./gmsh" "../demos/simple_geo/homology.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/indheat.geo "./gmsh" "../demos/simple_geo/indheat.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/machine.geo "./gmsh" "../demos/simple_geo/machine.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/piece-extr-rec.geo "./gmsh" "../demos/simple_geo/piece-extr-rec.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/piece-extr.geo "./gmsh" "../demos/simple_geo/piece-extr.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/piece.geo "./gmsh" "../demos/simple_geo/piece.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/pripyrtet.geo "./gmsh" "../demos/simple_geo/pripyrtet.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/sphere-discrete.geo "./gmsh" "../demos/simple_geo/sphere-discrete.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/sphere.geo "./gmsh" "../demos/simple_geo/sphere.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/splines.geo "./gmsh" "../demos/simple_geo/splines.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/square_regular.geo "./gmsh" "../demos/simple_geo/square_regular.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/tower.geo "./gmsh" "../demos/simple_geo/tower.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/transfinite.geo "./gmsh" "../demos/simple_geo/transfinite.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/struct/Exists_GetForced.geo "./gmsh" "../demos/struct/Exists_GetForced.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/struct/struct.geo "./gmsh" "../demos/struct/struct.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t1.geo "./gmsh" "../tutorial/t1.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t10.geo "./gmsh" "../tutorial/t10.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t11.geo "./gmsh" "../tutorial/t11.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t12.geo "./gmsh" "../tutorial/t12.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t13.geo "./gmsh" "../tutorial/t13.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t14.geo "./gmsh" "../tutorial/t14.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t15.geo "./gmsh" "../tutorial/t15.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t16.geo "./gmsh" "../tutorial/t16.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t17.geo "./gmsh" "../tutorial/t17.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t2.geo "./gmsh" "../tutorial/t2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t3.geo "./gmsh" "../tutorial/t3.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t4.geo "./gmsh" "../tutorial/t4.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t5.geo "./gmsh" "../tutorial/t5.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t6.geo "./gmsh" "../tutorial/t6.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t7.geo "./gmsh" "../tutorial/t7.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t8.geo "./gmsh" "../tutorial/t8.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t9.geo "./gmsh" "../tutorial/t9.geo" "-3" "-nopopup" "-o" "./tmp.msh")
subdirs("Common")
subdirs("Numeric")
subdirs("Geo")
subdirs("Mesh")
subdirs("Solver")
subdirs("Post")
subdirs("Plugin")
subdirs("Parser")
subdirs("Fltk")
subdirs("contrib/onelab")
subdirs("contrib/mpeg_encode")
subdirs("Graphics")
subdirs("contrib/ANN")
subdirs("contrib/ALGLIB")
subdirs("contrib/DiscreteIntegration")
subdirs("contrib/HighOrderMeshOptimizer")
subdirs("contrib/MeshOptimizer")
subdirs("contrib/MeshQualityOptimizer")
subdirs("contrib/domhex")
subdirs("contrib/QuadTri")
subdirs("contrib/kbipack")
subdirs("contrib/MathEx")
subdirs("contrib/metis")
subdirs("contrib/voro++")
subdirs("contrib/blossom")
subdirs("contrib/Netgen")
subdirs("contrib/bamg")
subdirs("contrib/mmg3d")
subdirs("contrib/hxt")
